[tool.poetry]
name = "nonebot-plugin-picstatus"
version = "0.2.4"
description = "A NoneBot2 plugin generates a picture which shows the status of current device"
authors = ["student_2333 <lgc2333@126.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8,<4.0"
Pillow = "^9.2.0"
psutil = "^5.9.2"
aiofiles = "^22.1.0"
nonebot2 = "^2.0.0-beta.5"
aiohttp = "^3.8.3"
nonebot-adapter-onebot = "^2.1.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
